config/routes.rb
Rails.application.routes.draw do
  resources :pacientes

  root 'pacientes#index'
  get '/index' => 'home#index'
  get '/about' => 'home#about', as: :about
  

end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  enum sangue: [ "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" ]
#  enum sangue: [ :Apositivo, :Anegativo, :Bpositivo, :Bnegativo, :Opositivo, :Onegativo, :ABpositivo, :ABnegativo ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  def create
    @paciente = Paciente.new(paciente_params)

    if @paciente.save
      redirect_to pacientes_url, notice: 'Paciente criado com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /pacientes/1
  def update
    if @paciente.update(paciente_params)
      redirect_to pacientes_url, notice: 'Paciente atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /pacientes/1
  def destroy
    @paciente.destroy
    redirect_to pacientes_url, notice: 'Paciente foi removido.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def paciente_params
      params.require(:paciente).permit(:nome, :email, :telefone, :data_nascimento, :sexo, :estado_civil, :profissao, :trabalha, :sangue, :fumante, :etilista, :cirurgias, :doencas_paternas, :doencas_maternas, :historico_peso)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-error',
    alert: 'alert-block',
    notice: 'alert-success'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "#{bootstrap_class_for(msg_type)}") do
        concat content_tag(:button, '×'.html_safe, class: "close", data: { dismiss: 'alert' })
          concat message
      end)
    end
    nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/home/about.html.erb
<div class="jumbotron">
  <h1>Anamnese</h1>
  <p>Sistema de Registro de Avaliações Nutricionais.</p>
</div>

app/views/home/index.html.erb
<h1>Anamnese</h1>
<p>Sistema de Registro de Avaliações Nutricionais.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anamnese</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <span class="brand-name">Anamnese</span> -->
        <%= link_to 'Anamnese', root_path, class: 'brand-name' %>
        <%= link_to image_tag('logo_isabela_completa_80.png'), root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Pacientes',  root_path,  class: ('active' if params[:controller] == 'pacientes') %></li>
          <li><%= link_to 'About', about_path, class: ('active' if params[:controller] == 'home') %></li>
        </ul>
      </div>
    </nav>
  </header>
 
  <div class="container">
    
    <%= flash_messages %>
    
    <div class="row">
      <div class="col-md-12">
        <!-- <div class="jumbotron"> -->
          <%= yield %>
        <!-- </div> -->
      </div>
    </div>
  </div>

</body>
</html>

app/views/pacientes/_dados_historicos.html.erb
<div class="form-inputs">
  <%= f.input :cirurgias, input_html: { cols: "28" } %>
  <%= f.input :doencas_paternas, input_html: { cols: "28" }  %>
  <%= f.input :doencas_maternas, input_html: { cols: "28" }  %>
  <%= f.input :historico_peso, input_html: { cols: "28" }  %>
</div>

app/views/pacientes/_dados_pessoais.html.erb
<div class="form-inputs">
  <%= f.input :nome, input_html: { size: "30" } %>
  <%= f.input :email, input_html: { size: "30" } %>
  <%= f.input :telefone, as: :tel %>
  <%= f.input :data_nascimento, as: :date, start_year: Date.today.year - 10,
              end_year: Date.today.year - 85, discard_day: true,
              order: [:month, :year] %>     
  <%= f.input :estado_civil, as: :select, collection: [:solteiro, :casado, :separado, :viuvo] %>
  <%= f.input :profissao, input_html: { size: "30" } %>
  <%= f.input :sangue %>
  <div class="form-group">
    <%= f.label :mulher %>
    <%= f.input_field :sexo, as: :boolean, checked_value: "F", unchecked_value: "M",boolean_style: :inline %>
    <%= f.label :trabalha %>
    <%= f.input_field :trabalha, as: :boolean, boolean_style: :inline %>
    <%= f.label :fuma %>
    <%= f.input_field :fumante, as: :boolean, boolean_style: :inline %>
    <%= f.label :bebe %>
    <%= f.input_field :etilista, as: :boolean, boolean_style: :inline %>
  </div>
</div>

app/views/pacientes/_field_wrapper.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= title %></div>
  <div class="panel-body">
    <%= yield %>
  </div>
</div>

app/views/pacientes/_form.html.erb
<%= simple_form_for @paciente, html: { class: "form-inline" }, 
    wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
    } do |f| %>
    <%= f.error_notification %>
    <div class="row">
      <%= render partial: 'dados_pessoais', layout: 'field_wrapper', locals: { title: 'Dados Pessoais', f: f } %>

      <%= render partial: 'dados_historicos', layout: 'field_wrapper', locals: { title: 'Dados Históricos', f: f } %>
    </div>
    <div class="row">
      <div class="form-actions">
        <%= link_to 'Cancelar', pacientes_path, class: "btn btn-default btn-lg" %>
        <%= f.button :submit, "Salvar Paciente", class: "btn btn-success btn-lg" %>
      </div>
    </div>
<% end %>

app/views/pacientes/edit.html.erb
<h2>Edição de dados do Paciente</h2>

<%= render 'form' %>

app/views/pacientes/index.html.erb
<h2>Pacientes</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <!-- <th colspan="5"></th> -->
      <th class="text-center">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.telefone %></td>
        <td class="text-center">
          <%= link_to sanitize("<span class='glyphicon glyphicon-info-sign'></span>"), paciente, id: "bt-show", class: "btn btn-primary btn-sm", title:"Detalhes do Paciente" %>
          <%= link_to sanitize("<span class='glyphicon glyphicon-pencil'></span>"), edit_paciente_path(paciente), id: "bt-edit", class: "btn btn-primary btn-sm", title:"Editar dados do Paciente" %>
          <%= link_to sanitize("<span class='glyphicon glyphicon-list-alt'></span>"), edit_paciente_path(paciente), id: "bt-anamnese", class: "btn btn-primary btn-sm", title:"Criar Nova Anamnese para este Paciente" %>
          <%= link_to sanitize("<span class='glyphicon glyphicon-time'></span>"), edit_paciente_path(paciente), id: "bt-historico", class: "btn btn-primary btn-sm", title:"Histórico de Anamneses do Paciente" %>
          <%= link_to sanitize("<span class='glyphicon glyphicon-trash'></span>"),  paciente, method: :delete, data: { confirm: 'Você está prestes a excluir este paciente de forma definitiva. Tem certeza de que deseja tomar essa ação?' }, id: "bt-destroy", class: "btn btn-primary btn-sm", title:"Excluir Paciente. CUIDADO!" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Paciente', new_paciente_path, class: "btn btn-success btn-lg" %>

app/views/pacientes/new.html.erb
<h2>Novo Paciente</h2>

<%= render 'form' %>

app/views/pacientes/show.html.erb
<div class="row">
  <div class="panel panel-primary">
    <div class="panel-heading">Dados Pessoais</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-3">
          <strong>Nome:</strong> <%= @paciente.nome %>
        </div>
        <div class="col-xs-3">
          <strong>Email:</strong>
          <%= @paciente.email %>
        </div>
        <div class="col-xs-3">
          <strong>Telefone:</strong>
          <%= @paciente.telefone %>
        </div>
        <div class="col-xs-3">
          <strong>Data nascimento:</strong>
          <%= @paciente.data_nascimento %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          <strong>Sexo:</strong>
          <%= @paciente.sexo == "M" ? "Masculino":"Feminino" %>
        </div>
        <div class="col-xs-3">
          <strong>Estado civil:</strong>
          <%= @paciente.estado_civil %>
        </div>
        <div class="col-xs-3">
          <strong>Profissao:</strong>
          <%= @paciente.profissao %>
        </div>
        <div class="col-xs-3">
          <strong>Trabalha:</strong>
          <%= @paciente.trabalha ? "Sim":"Não" %>
        </div>
      </div>  
      <div class="row">
        <div class="col-xs-3">
          <strong>Tipo sanguineo:</strong>
          <%= @paciente.sangue %>
        </div>
        <div class="col-xs-3">
          <strong>Fumante:</strong>
          <%= @paciente.fumante ? "Sim":"Não" %>
        </div>
        <div class="col-xs-3">
          <strong>Etilista:</strong>
          <%= @paciente.etilista ? "Sim":"Não" %>
        </div>
        <div class="col-xs-3">
        </div>
      </div>  
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">Dados Pessoais</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-3">
          <strong>Cirurgias:</strong><br/>
          <%= @paciente.cirurgias %>
        </div>
        <div class="col-xs-3">
          <strong>Doencas paternas:</strong><br/>
          <%= @paciente.doencas_paternas %>
        </div>
        <div class="col-xs-3">
          <strong>Doencas maternas:</strong><br/>
          <%= @paciente.doencas_maternas %>
        </div>
        <div class="col-xs-3">
          <strong>Historico peso:</strong><br/>
          <%= @paciente.historico_peso %>
        </div>
      </div>  
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>